version: '3'
services:
  ### Posgres database for Events
  db-inventory:
    container_name: db-events
    image: postgres:15.2
    restart: unless-stopped
    environment:
      POSTGRES_DB: ms_events 0
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - 5431:5431
    expose:
      - 5431
    command: -p 5431

  ### Posgres database for Products
  db-products:
    container_name: db-users
    image: postgres:15.2
    restart: unless-stopped
    environment:
      POSTGRES_DB: ms_users
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - 5432:5432
    expose:
      - 5432
    command: -p 5432

  ### Postgres database for Orders
  db-orders:
    container_name: db-interactions
    image: postgres:15.2
    restart: unless-stopped
    environment:
      POSTGRES_DB: ms_interactions
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - 5433:5433
    expose:
      - 5433
    command: -p 5433

  ### Posgres database for Keycloak
  db-keycloak:
    image: postgres:15.2
    restart: unless-stopped
    environment:
      POSTGRES_DB: db_keycloak
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - 5434:5434
    expose:
      - 5434
    command: -p 5434

  ### Keycloak
  keycloak:
    image: quay.io/keycloak/keycloak:21.0.2
    command: ["start-dev"]
    ports:
      - 8181:8181
    expose:
      - 8181
    depends_on:
      - db-keycloak
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: db-keycloak
      DB_DATABASE: db_keycloak
      DB_PORT: 5434
      DB_USER: admin
      DB_PASSWORD: admin
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HTTP_PORT: 8181

  ### Zookeeper
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  ### Kafka
  kafka:
    image: confluentinc/cp-kafka:7.4.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

  ### Zipkin
  zipkin:
    image: openzipkin/zipkin:2.24.2
    ports:
      - "9411:9411"

  ### Prometheus
  prometheus:
    image: prom/prometheus:v2.46.0
    ports:
      - "9090:9090"
    volumes:
      - ./files/prometheus.yml:/etc/prometheus/prometheus.yml

  ### Grafana
  grafana:
    image: grafana/grafana-oss:10.0.3
    restart: unless-stopped
    ports:
      - "3000:3000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    links:
      - prometheus
    volumes:
      - ./files/grafana:/var/lib/grafana
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_SECURITY_ADMIN_USER: admin
    depends_on:
      - prometheus